// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"AdjustPictureGraphical","status":true,"description":"Plugin that adjust picture to graphical","parameters":{"GridSize":"48","TestMapId":"-1"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"EventEffects","status":true,"description":"[Ver 1.1.2] set various effects to events and player","parameters":{}},
{"name":"EventCommandByCode","status":true,"description":"Plugin for Event Command Execution via Code Specification","parameters":{}},
{"name":"ChangeSelectItemWindowMZ","status":true,"description":"Change the various settings of item selecting window.","parameters":{"Switch ID":"1","Max Columns":"1","Visible Rows":"8","X position":"-1","Y position":"-1","Width":"-1"}},
{"name":"ExtraImage","status":true,"description":"Extra Image Display Per Scene Plugin","parameters":{"ImageList":"[]"}},
{"name":"SetFieldSkillIdMZ","status":true,"description":"Set Different Skill ID on Map.","parameters":{}},
{"name":"PluginBaseFunction","status":true,"description":"プラグイン共通関数","parameters":{}},
{"name":"RegionBase","status":true,"description":"Region Base Plugin","parameters":{"regionList":"[]","terrainTagList":"[]"}},
{"name":"AltMenuScreen2MZ","status":true,"description":"Yet another menu screen layout","parameters":{"allowWindowDisp":"true","maxColsMenu":"1","commandRows":"8","commandCols":"1","isDisplayStatus":"false","display map name":"true","location string":"Location:","bgBitmapMenu":"","doesNotSetItemScene":"false","bgBitmapItem":"","doesNotSetSkillScene":"false","bgBitmapSkill":"","doesNotSetEquipScene":"false","bgBitmapEquip":"","doesNotSetStatusScene":"false","bgBitmapStatus":"","doesNotSetOptionScene":"false","bgBitmapOptions":"","doesNotSetSaveScene":"false","bgBitmapFile":"","doesNotSetEndScene":"false","bgBitmapGameEnd":""}},
{"name":"wasdKeyMZ","status":true,"description":"","parameters":{}},
{"name":"SmoothTouchMove","status":true,"description":"on touch move, player can through events under the player","parameters":{}}
];
